### ISSUE TITLE
Is the Sessions functionality implemented?

### ISSUE THREAD

**Issue by steven-luabase** [ScrapingBee/scrapingbee-python#12]
I saw that `session_id` is a possible param in the docs:
https://www.scrapingbee.com/documentation/#session_id

Having some trouble getting it to work and couldn't find any mention of it in this repo so was wondering if this is an active feature. I'm trying to first use a GET request to input login info and then use a PUT request in the same session to pull some data.

The rough outline of my code is below:
```
client = ScrapingBeeClient(api_key='API_KEY')
cookie_string = 'user=me;password=pw'


get_response = client.get(
    url = 'https://someloginurl.com',
    cookies=cookie_string,
    params={ 
        "premium_proxy": "true", 
        'country_code':'us',
        'session_id': '123'
    },  
    headers=headers,
)

post_response = client.post(
    url='https://someloginurl.com/data', 
    cookies=cookie_string,
    params = {
      "premium_proxy": "true", 
      'country_code':'us',
      'session_id': '123'
    },
)
```

I am able to authenticate the first GET request but when I try to followup with the POST request the data I need is still behind a login. How do I chain the two requests together into the same session?

**Comment by daolf** [comment]
Hi there and sorry about the late reply.

Yes the session feature is implemented and working well.

There's probably an issue with your POST request, either a param thing or a header thing. 

Feel free to reach out to our support, we will help you fixing it!

Cheers
