### ISSUE TITLE
Typo with `js_scenario` being mislabelled as `js_scenario`

### ISSUE THREAD

**Issue by denwong47** [ScrapingBee/scrapingbee-python#17]
Hi maintainers,

I may have a tiny issue for you:

In `README.md` the `params` has a `dict` key named `json_scenario`, but this key does not actually get processed. It should have been `js_scenario` as per [scrapingbee/utils.py](https://github.com/ScrapingBee/scrapingbee-python/blob/e8d00487e22acb2b92ad45974f51875c7a87e4a5/scrapingbee/utils.py#L49).

This also affects PyPi.

Thanks in advance!

**Comment by denwong47** [comment]
Actually in the same `dict`, `block_resources` was misspelt as `block_ressources` too.

**Comment by daolf** [comment]
Hi there and thank you so much for reporting this. 

This is now fixed in v2.0.1!
